// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens (
    id,
    user_id,
    token_hash,
    type,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, token_hash, type, expires_at, used_at, inserted_at
`

type CreateEmailTokenParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	Type      string             `json:"type"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, createEmailToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Type,
		arg.ExpiresAt,
	)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.InsertedAt,
	)
	return i, err
}

const deleteEmailTokensByUserID = `-- name: DeleteEmailTokensByUserID :exec
DELETE FROM email_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteEmailTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailTokensByUserID, userID)
	return err
}

const deleteExpiredEmailTokens = `-- name: DeleteExpiredEmailTokens :execrows
DELETE FROM email_tokens
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredEmailTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailTokenByHash = `-- name: GetEmailTokenByHash :one
SELECT id, user_id, token_hash, type, expires_at, used_at, inserted_at
FROM email_tokens
WHERE token_hash = $1
`

func (q *Queries) GetEmailTokenByHash(ctx context.Context, tokenHash []byte) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailTokenByHash, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.InsertedAt,
	)
	return i, err
}

const getEmailTokenByHashActive = `-- name: GetEmailTokenByHashActive :one
SELECT id, user_id, token_hash, type, expires_at, used_at, inserted_at
FROM email_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetEmailTokenByHashActive(ctx context.Context, tokenHash []byte) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailTokenByHashActive, tokenHash)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.InsertedAt,
	)
	return i, err
}

const getEmailTokenByHashActiveType = `-- name: GetEmailTokenByHashActiveType :one
SELECT id, user_id, token_hash, type, expires_at, used_at, inserted_at
FROM email_tokens
WHERE token_hash = $1
  AND type = $2
  AND used_at IS NULL
  AND expires_at > now()
`

type GetEmailTokenByHashActiveTypeParams struct {
	TokenHash []byte `json:"token_hash"`
	Type      string `json:"type"`
}

func (q *Queries) GetEmailTokenByHashActiveType(ctx context.Context, arg GetEmailTokenByHashActiveTypeParams) (EmailToken, error) {
	row := q.db.QueryRow(ctx, getEmailTokenByHashActiveType, arg.TokenHash, arg.Type)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.InsertedAt,
	)
	return i, err
}

const invalidateActiveEmailTokensByUserAndType = `-- name: InvalidateActiveEmailTokensByUserAndType :exec
UPDATE email_tokens
SET used_at = now()
WHERE user_id = $1
  AND type = $2
  AND used_at IS NULL
`

type InvalidateActiveEmailTokensByUserAndTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) InvalidateActiveEmailTokensByUserAndType(ctx context.Context, arg InvalidateActiveEmailTokensByUserAndTypeParams) error {
	_, err := q.db.Exec(ctx, invalidateActiveEmailTokensByUserAndType, arg.UserID, arg.Type)
	return err
}

const markEmailTokenUsed = `-- name: MarkEmailTokenUsed :one
UPDATE email_tokens
SET used_at = now()
WHERE id = $1
  AND used_at IS NULL
RETURNING id, user_id, token_hash, type, expires_at, used_at, inserted_at
`

func (q *Queries) MarkEmailTokenUsed(ctx context.Context, id pgtype.UUID) (EmailToken, error) {
	row := q.db.QueryRow(ctx, markEmailTokenUsed, id)
	var i EmailToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.InsertedAt,
	)
	return i, err
}
