// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	Type       string             `json:"type"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
}

type OauthIdentity struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Provider      string             `json:"provider"`
	ProviderUid   string             `json:"provider_uid"`
	ProviderEmail string             `json:"provider_email"`
	InsertedAt    pgtype.Timestamptz `json:"inserted_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	InsertedAt pgtype.Timestamptz `json:"inserted_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	DisplayName     string             `json:"display_name"`
	Role            string             `json:"role"`
	InsertedAt      pgtype.Timestamptz `json:"inserted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	AvatarMetadata  []byte             `json:"avatar_metadata"`
}
