// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_identities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (
    id,
    user_id,
    provider,
    provider_uid,
    provider_email
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (provider, provider_uid)
DO UPDATE
SET provider_email = EXCLUDED.provider_email
RETURNING id, user_id, provider, provider_uid, provider_email, inserted_at
`

type CreateOAuthIdentityParams struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	Provider      string      `json:"provider"`
	ProviderUid   string      `json:"provider_uid"`
	ProviderEmail string      `json:"provider_email"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUid,
		arg.ProviderEmail,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.ProviderEmail,
		&i.InsertedAt,
	)
	return i, err
}

const getOAuthIdentityByProviderUID = `-- name: GetOAuthIdentityByProviderUID :one
SELECT id, user_id, provider, provider_uid, provider_email, inserted_at
FROM oauth_identities
WHERE provider = $1
  AND provider_uid = $2
`

type GetOAuthIdentityByProviderUIDParams struct {
	Provider    string `json:"provider"`
	ProviderUid string `json:"provider_uid"`
}

func (q *Queries) GetOAuthIdentityByProviderUID(ctx context.Context, arg GetOAuthIdentityByProviderUIDParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityByProviderUID, arg.Provider, arg.ProviderUid)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.ProviderEmail,
		&i.InsertedAt,
	)
	return i, err
}

const getOAuthIdentityByUserProvider = `-- name: GetOAuthIdentityByUserProvider :one
SELECT id, user_id, provider, provider_uid, provider_email, inserted_at
FROM oauth_identities
WHERE user_id = $1
  AND provider = $2
`

type GetOAuthIdentityByUserProviderParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) GetOAuthIdentityByUserProvider(ctx context.Context, arg GetOAuthIdentityByUserProviderParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentityByUserProvider, arg.UserID, arg.Provider)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUid,
		&i.ProviderEmail,
		&i.InsertedAt,
	)
	return i, err
}

const listOAuthIdentitiesByUserID = `-- name: ListOAuthIdentitiesByUserID :many
SELECT id, user_id, provider, provider_uid, provider_email, inserted_at
FROM oauth_identities
WHERE user_id = $1
ORDER BY inserted_at ASC
`

func (q *Queries) ListOAuthIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]OauthIdentity, error) {
	rows, err := q.db.Query(ctx, listOAuthIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthIdentity
	for rows.Next() {
		var i OauthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUid,
			&i.ProviderEmail,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
