// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error)
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEmailTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteExpiredEmailTokens(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteSessionByID(ctx context.Context, id pgtype.UUID) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error
	DeleteSessionsByUserID(ctx context.Context, userID pgtype.UUID) error
	GetEmailTokenByHash(ctx context.Context, tokenHash []byte) (EmailToken, error)
	GetEmailTokenByHashActive(ctx context.Context, tokenHash []byte) (EmailToken, error)
	GetEmailTokenByHashActiveType(ctx context.Context, arg GetEmailTokenByHashActiveTypeParams) (EmailToken, error)
	GetOAuthIdentityByProviderUID(ctx context.Context, arg GetOAuthIdentityByProviderUIDParams) (OauthIdentity, error)
	GetOAuthIdentityByUserProvider(ctx context.Context, arg GetOAuthIdentityByUserProviderParams) (OauthIdentity, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetSessionByTokenHashActive(ctx context.Context, tokenHash []byte) (Session, error)
	GetUserByDisplayName(ctx context.Context, lower string) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InvalidateActiveEmailTokensByUserAndType(ctx context.Context, arg InvalidateActiveEmailTokensByUserAndTypeParams) error
	ListOAuthIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]OauthIdentity, error)
	LockUserByID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	MarkEmailTokenUsed(ctx context.Context, id pgtype.UUID) (EmailToken, error)
	MarkUserEmailVerified(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateSessionExpiresAt(ctx context.Context, arg UpdateSessionExpiresAtParams) (Session, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error)
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
