// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    password_hash,
    display_name,
    role,
    avatar_metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
`

type CreateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	DisplayName    string      `json:"display_name"`
	Role           string      `json:"role"`
	AvatarMetadata []byte      `json:"avatar_metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
		arg.AvatarMetadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}

const getUserByDisplayName = `-- name: GetUserByDisplayName :one
SELECT id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
FROM users
WHERE lower(display_name) = lower($1)
`

func (q *Queries) GetUserByDisplayName(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDisplayName, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
FROM users
WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}

const lockUserByID = `-- name: LockUserByID :one
SELECT id
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockUserByID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockUserByID, id)
	err := row.Scan(&id)
	return id, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE users
SET
    email_verified_at = COALESCE(email_verified_at, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET
    display_name = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
`

type UpdateUserDisplayNameParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
UPDATE users
SET
    password_hash = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
`

type UpdateUserPasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    display_name = $2,
    avatar_metadata = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
`

type UpdateUserProfileParams struct {
	ID             pgtype.UUID `json:"id"`
	DisplayName    string      `json:"display_name"`
	AvatarMetadata []byte      `json:"avatar_metadata"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName, arg.AvatarMetadata)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET
    role = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, display_name, role, inserted_at, updated_at, email_verified_at, avatar_metadata
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.InsertedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.AvatarMetadata,
	)
	return i, err
}
